# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArchTabs
                                 A QGIS plugin
 This plugin allows you to get border description tables.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-12
        copyright            : (C) 2022 by Valery
        email                : shigaevaler@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ArchTabs class from file ArchTabs.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ArchTabs import ArchTabs
    return ArchTabs(iface)
